Repository ebi-gene-expression-group/atlas-components, pull requests merged in 2025-03, with the labels that each got.

#195 Chore/fix security vulnerability in atlas tsne widget
  packages/scxa-tsne-widget/html/Demo.js
  packages/scxa-tsne-widget/html/index.html
  packages/scxa-tsne-widget/package.json
  packages/scxa-tsne-widget/src/TSnePlotWidget.js
  packages/scxa-tsne-widget/src/index.js
  packages/scxa-tsne-widget/webpack.config.js
Labels: dependencies, improvement

#194 Fix security vulnerability in the atlas bioentity information
  packages/atlas-bioentity-information/html/Demo.js
  packages/atlas-bioentity-information/package-lock.json
  packages/atlas-bioentity-information/package.json
  packages/atlas-bioentity-information/webpack.config.js
Labels: improvement, technical debt, chore

#198 Fix security vulnerability in cell type wheel
  packages/scxa-cell-type-wheel/package-lock.json
  packages/scxa-cell-type-wheel/package.json
Labels: dependencies, improvement, chore

#199 Fix security vulnerabilities in gene search form
  packages/scxa-gene-search-form/README.md
  packages/scxa-gene-search-form/__test__/__snapshots__/Autocomplete.test.js.snap
  packages/scxa-gene-search-form/__test__/__snapshots__/GeneSearchForm.test.js.snap
  packages/scxa-gene-search-form/__test__/fetch-mocks/handlers.js
  packages/scxa-gene-search-form/html/index.html
  packages/scxa-gene-search-form/html/render.js
  packages/scxa-gene-search-form/jest.setup.js
  packages/scxa-gene-search-form/package-lock.json
  packages/scxa-gene-search-form/package.json
  packages/scxa-gene-search-form/src/LabelledSelect.js
  packages/scxa-gene-search-form/src/ebiVfReactSelectReplacements.js
  packages/scxa-gene-search-form/webpack.config.js
Labels: dependencies, improvement, chore

#207 Fix security vulnerability in atlas homepage card
  packages/atlas-homepage-cards/README.md
  packages/atlas-homepage-cards/__test__/Card.test.js
  packages/atlas-homepage-cards/__test__/CarouselCardsRow.test.js
  packages/atlas-homepage-cards/__test__/ExtendableCard.test.js
  packages/atlas-homepage-cards/__test__/ResponsiveCardsRow.test.js
  packages/atlas-homepage-cards/__test__/__snapshots__/Card.test.js.snap
  packages/atlas-homepage-cards/__test__/__snapshots__/CarouselCardsRow.test.js.snap
  packages/atlas-homepage-cards/__test__/__snapshots__/ExtendableCard.test.js.snap
  packages/atlas-homepage-cards/__test__/__snapshots__/ResponsiveCardsRow.test.js.snap
  packages/atlas-homepage-cards/html/AnimalSpeciesSummary.js
  packages/atlas-homepage-cards/html/CarouselCardsPanelDemo.js
  packages/atlas-homepage-cards/html/ExperimentsPanelDemo.js
  packages/atlas-homepage-cards/html/ResponsiveCardsRowWithExtCardsDemo.js
  packages/atlas-homepage-cards/html/index.html
  packages/atlas-homepage-cards/jest.setup.js
  packages/atlas-homepage-cards/package.json
  packages/atlas-homepage-cards/webpack.config.js
Labels: dependencies

#205 Fix security vulnerabilities in scxa experiment page
  packages/scxa-experiment-page/package-lock.json
  packages/scxa-experiment-page/package.json
  packages/scxa-experiment-page/webpack.config.js
  packages/scxa-tsne-plot/package-lock.json
Labels: dependencies, improvement
